/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bv3`; params?: Router.UnknownInputParams; } | { pathname: `/cafepropsandemitv10`; params?: Router.UnknownInputParams; } | { pathname: `/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/clicker`; params?: Router.UnknownInputParams; } | { pathname: `/components1`; params?: Router.UnknownInputParams; } | { pathname: `/decryptpages`; params?: Router.UnknownInputParams; } | { pathname: `/elevator`; params?: Router.UnknownInputParams; } | { pathname: `/graphics`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mnmx`; params?: Router.UnknownInputParams; } | { pathname: `/plotly3d`; params?: Router.UnknownInputParams; } | { pathname: `/tableChess`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/weather`; params?: Router.UnknownInputParams; } | { pathname: `/weathercomponents`; params?: Router.UnknownInputParams; } | { pathname: `/weatherv2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/types/weather.types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bv3`; params?: Router.UnknownOutputParams; } | { pathname: `/cafepropsandemitv10`; params?: Router.UnknownOutputParams; } | { pathname: `/calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/clicker`; params?: Router.UnknownOutputParams; } | { pathname: `/components1`; params?: Router.UnknownOutputParams; } | { pathname: `/decryptpages`; params?: Router.UnknownOutputParams; } | { pathname: `/elevator`; params?: Router.UnknownOutputParams; } | { pathname: `/graphics`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mnmx`; params?: Router.UnknownOutputParams; } | { pathname: `/plotly3d`; params?: Router.UnknownOutputParams; } | { pathname: `/tableChess`; params?: Router.UnknownOutputParams; } | { pathname: `/test`; params?: Router.UnknownOutputParams; } | { pathname: `/weather`; params?: Router.UnknownOutputParams; } | { pathname: `/weathercomponents`; params?: Router.UnknownOutputParams; } | { pathname: `/weatherv2`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/types/weather.types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bv3${`?${string}` | `#${string}` | ''}` | `/cafepropsandemitv10${`?${string}` | `#${string}` | ''}` | `/calculator${`?${string}` | `#${string}` | ''}` | `/clicker${`?${string}` | `#${string}` | ''}` | `/components1${`?${string}` | `#${string}` | ''}` | `/decryptpages${`?${string}` | `#${string}` | ''}` | `/elevator${`?${string}` | `#${string}` | ''}` | `/graphics${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mnmx${`?${string}` | `#${string}` | ''}` | `/plotly3d${`?${string}` | `#${string}` | ''}` | `/tableChess${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | `/weather${`?${string}` | `#${string}` | ''}` | `/weathercomponents${`?${string}` | `#${string}` | ''}` | `/weatherv2${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/types/weather.types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bv3`; params?: Router.UnknownInputParams; } | { pathname: `/cafepropsandemitv10`; params?: Router.UnknownInputParams; } | { pathname: `/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/clicker`; params?: Router.UnknownInputParams; } | { pathname: `/components1`; params?: Router.UnknownInputParams; } | { pathname: `/decryptpages`; params?: Router.UnknownInputParams; } | { pathname: `/elevator`; params?: Router.UnknownInputParams; } | { pathname: `/graphics`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mnmx`; params?: Router.UnknownInputParams; } | { pathname: `/plotly3d`; params?: Router.UnknownInputParams; } | { pathname: `/tableChess`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/weather`; params?: Router.UnknownInputParams; } | { pathname: `/weathercomponents`; params?: Router.UnknownInputParams; } | { pathname: `/weatherv2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/types/weather.types`; params?: Router.UnknownInputParams; };
    }
  }
}
